import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/styles/globals.css';
import { Header } from '@/components/layout';
import { Providers } from '@/providers';
import { Container } from '@mui/material';
import NextTopLoader from 'nextjs-toploader';
import { FC, PropsWithChildren } from 'react';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Urbio Blog',
	description: 'Generated by create next app',
};

const RootLayout: FC<Readonly<PropsWithChildren>> = ({ children }) => (
	<html lang="en">
		<body className={`${poppins.variable} antialiased`}>
			<Providers>
				<NextTopLoader />
				<Container maxWidth="xl" sx={{ maxWidth: '1200px' }}>
					<Header />
					{children}
				</Container>
			</Providers>
		</body>
	</html>
);

export default RootLayout;
